[hooks]
pre-commit = "cargo test"
pre-push = ["cargo check", "cargo fmt -- --check"]
post-commit = "echo All changes were committed"
post-push = "echo All commits were pushed"

[logging]
verbose = true
